#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 20, 2018 03:27:09 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import msg_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    msg_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    msg_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("623x450+522+158")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.02, relheight=0.99, relwidth=1.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=625)

        self.Message1 = Message(self.Frame1)
        self.Message1.place(relx=0.24, rely=0.04, relheight=0.14, relwidth=0.4)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''pour lire Passer la carte Rfid''')
        self.Message1.configure(width=250)

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(self.Frame1)
        self.TNotebook1.place(relx=0.02, rely=0.31, relheight=0.67
                , relwidth=0.97)
        self.TNotebook1.configure(width=604)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t0 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t0, padding=3)
        self.TNotebook1.tab(0, text="Page 1",compound="left",underline="-1",)
        self.TNotebook1_t0.configure(background="#d9d9d9")
        self.TNotebook1_t0.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t0.configure(highlightcolor="black")
        self.TNotebook1_t0.configure(width=600)
        self.TNotebook1_t1 = Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(1, text="Page 2",compound="left",underline="-1",)
        self.TNotebook1_t1.configure(background="#d9d9d9")
        self.TNotebook1_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t1.configure(highlightcolor="black")

        self.TLabelframe1 = ttk.Labelframe(self.TNotebook1_t0)
        self.TLabelframe1.place(relx=0.02, rely=0.04, relheight=0.2
                , relwidth=0.25)
        self.TLabelframe1.configure(text='''PRENOM''')
        self.TLabelframe1.configure(width=150)
        self.TLabelframe1.configure(takefocus="0")

        self.TEntry1 = ttk.Entry(self.TLabelframe1)
        self.TEntry1.place(relx=0.07, rely=0.36, relheight=0.38, relwidth=0.84
                , y=-12, h=12)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.TLabelframe1_1 = ttk.Labelframe(self.TNotebook1_t0)
        self.TLabelframe1_1.place(relx=0.02, rely=0.33, relheight=0.2
                , relwidth=0.25)
        self.TLabelframe1_1.configure(text='''NOM''')
        self.TLabelframe1_1.configure(width=150)
        self.TLabelframe1_1.configure(takefocus="0")

        self.TEntry1_1 = ttk.Entry(self.TLabelframe1_1)
        self.TEntry1_1.place(relx=0.07, rely=0.36, relheight=0.38, relwidth=0.84
                , y=-12, h=12)
        self.TEntry1_1.configure(takefocus="")
        self.TEntry1_1.configure(cursor="ibeam")

        self.TLabelframe1_1_1 = ttk.Labelframe(self.TNotebook1_t0)
        self.TLabelframe1_1_1.place(relx=0.37, rely=0.04, relheight=0.2
                , relwidth=0.25)
        self.TLabelframe1_1_1.configure(text='''CLUB''')
        self.TLabelframe1_1_1.configure(width=150)
        self.TLabelframe1_1_1.configure(takefocus="0")

        self.TEntry1_1_1 = ttk.Entry(self.TLabelframe1_1_1)
        self.TEntry1_1_1.place(relx=0.07, rely=0.36, relheight=0.38
                , relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1.configure(takefocus="")
        self.TEntry1_1_1.configure(cursor="ibeam")

        self.TLabelframe1_1_1_1 = ttk.Labelframe(self.TNotebook1_t0)
        self.TLabelframe1_1_1_1.place(relx=0.37, rely=0.33, relheight=0.2
                , relwidth=0.25)
        self.TLabelframe1_1_1_1.configure(text='''DATEFIN''')
        self.TLabelframe1_1_1_1.configure(width=150)
        self.TLabelframe1_1_1_1.configure(takefocus="0")

        self.TEntry1_1_1_1 = ttk.Entry(self.TLabelframe1_1_1_1)
        self.TEntry1_1_1_1.place(relx=0.07, rely=0.36, relheight=0.38
                , relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1_1.configure(takefocus="")
        self.TEntry1_1_1_1.configure(cursor="ibeam")

        self.TLabelframe1_1_1_1_1 = ttk.Labelframe(self.TNotebook1_t0)
        self.TLabelframe1_1_1_1_1.place(relx=0.7, rely=0.04, relheight=0.2
                , relwidth=0.25)
        self.TLabelframe1_1_1_1_1.configure(text='''Uid''')
        self.TLabelframe1_1_1_1_1.configure(width=150)
        self.TLabelframe1_1_1_1_1.configure(takefocus="0")

        self.TEntry1_1_1_1_1 = ttk.Entry(self.TLabelframe1_1_1_1_1)
        self.TEntry1_1_1_1_1.place(relx=0.07, rely=0.36, relheight=0.38
                , relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1_1_1.configure(takefocus="")
        self.TEntry1_1_1_1_1.configure(cursor="ibeam")

        self.TLabelframe1_1_1_1_1_1 = ttk.Labelframe(self.TNotebook1_t0)
        self.TLabelframe1_1_1_1_1_1.place(relx=0.7, rely=0.33, relheight=0.2
                , relwidth=0.25)
        self.TLabelframe1_1_1_1_1_1.configure(text='''Tlabelframe''')
        self.TLabelframe1_1_1_1_1_1.configure(width=150)
        self.TLabelframe1_1_1_1_1_1.configure(takefocus="0")

        self.TEntry1_1_1_1_1_1 = ttk.Entry(self.TLabelframe1_1_1_1_1_1)
        self.TEntry1_1_1_1_1_1.place(relx=0.07, rely=0.36, relheight=0.38
                , relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1_1_1_1.configure(takefocus="")
        self.TEntry1_1_1_1_1_1.configure(cursor="ibeam")

        self.TButton1 = ttk.Button(self.TNotebook1_t0)
        self.TButton1.place(relx=0.4, rely=0.63, height=25, width=96)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Ecrire''')
        self.TButton1.configure(width=96)

        self.TLabelframe1_1_1_1_1_1_1 = ttk.Labelframe(self.TNotebook1_t1)
        self.TLabelframe1_1_1_1_1_1_1.place(relx=0.02, rely=0.07, relheight=0.2
                , relwidth=0.25)
        self.TLabelframe1_1_1_1_1_1_1.configure(text='''PRENOM''')
        self.TLabelframe1_1_1_1_1_1_1.configure(width=150)
        self.TLabelframe1_1_1_1_1_1_1.configure(takefocus="0")

        self.TEntry1_1_1_1_1_1_1 = ttk.Entry(self.TLabelframe1_1_1_1_1_1_1)
        self.TEntry1_1_1_1_1_1_1.place(relx=0.07, rely=0.36, relheight=0.38
                , relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1_1_1_1_1.configure(takefocus="")
        self.TEntry1_1_1_1_1_1_1.configure(cursor="ibeam")

        self.TLabelframe1_1_1_1_1_1_1_1 = ttk.Labelframe(self.TNotebook1_t1)
        self.TLabelframe1_1_1_1_1_1_1_1.place(relx=0.02, rely=0.37, relheight=0.2
                , relwidth=0.25)
        self.TLabelframe1_1_1_1_1_1_1_1.configure(text='''NOM''')
        self.TLabelframe1_1_1_1_1_1_1_1.configure(width=150)
        self.TLabelframe1_1_1_1_1_1_1_1.configure(takefocus="0")

        self.TEntry1_1_1_1_1_1_1_1 = ttk.Entry(self.TLabelframe1_1_1_1_1_1_1_1)
        self.TEntry1_1_1_1_1_1_1_1.place(relx=0.07, rely=0.36, relheight=0.38
                , relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1_1_1_1_1_1.configure(takefocus="")
        self.TEntry1_1_1_1_1_1_1_1.configure(cursor="ibeam")

        self.TLabelframe1_1_1_1_1_1_1_1_1 = ttk.Labelframe(self.TNotebook1_t1)
        self.TLabelframe1_1_1_1_1_1_1_1_1.place(relx=0.37, rely=0.07
                , relheight=0.2, relwidth=0.25)
        self.TLabelframe1_1_1_1_1_1_1_1_1.configure(text='''CLUB''')
        self.TLabelframe1_1_1_1_1_1_1_1_1.configure(width=150)
        self.TLabelframe1_1_1_1_1_1_1_1_1.configure(takefocus="0")

        self.TEntry1_1_1_1_1_1_1_1_1 = ttk.Entry(self.TLabelframe1_1_1_1_1_1_1_1_1)
        self.TEntry1_1_1_1_1_1_1_1_1.place(relx=0.07, rely=0.36, relheight=0.38
                , relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1_1_1_1_1_1_1.configure(takefocus="")
        self.TEntry1_1_1_1_1_1_1_1_1.configure(cursor="ibeam")

        self.TLabelframe1_1_1_1_1_1_1_1_1_1 = ttk.Labelframe(self.TNotebook1_t1)
        self.TLabelframe1_1_1_1_1_1_1_1_1_1.place(relx=0.37, rely=0.37
                , relheight=0.2, relwidth=0.25)
        self.TLabelframe1_1_1_1_1_1_1_1_1_1.configure(text='''DATEFIN''')
        self.TLabelframe1_1_1_1_1_1_1_1_1_1.configure(width=150)
        self.TLabelframe1_1_1_1_1_1_1_1_1_1.configure(takefocus="0")

        self.TEntry1_1_1_1_1_1_1_1_1_1 = ttk.Entry(self.TLabelframe1_1_1_1_1_1_1_1_1_1)
        self.TEntry1_1_1_1_1_1_1_1_1_1.place(relx=0.07, rely=0.36, relheight=0.38
                , relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1_1_1_1_1_1_1_1.configure(takefocus="")
        self.TEntry1_1_1_1_1_1_1_1_1_1.configure(cursor="ibeam")

        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1 = ttk.Labelframe(self.TNotebook1_t1)
        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1.place(relx=0.72, rely=0.07
                , relheight=0.2, relwidth=0.25)
        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1.configure(text='''Uid''')
        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1.configure(width=150)
        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1.configure(takefocus="0")

        self.TEntry1_1_1_1_1_1_1_1_1_1_1 = ttk.Entry(self.TLabelframe1_1_1_1_1_1_1_1_1_1_1)
        self.TEntry1_1_1_1_1_1_1_1_1_1_1.place(relx=0.07, rely=0.36
                , relheight=0.38, relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1_1_1_1_1_1_1_1_1.configure(takefocus="")
        self.TEntry1_1_1_1_1_1_1_1_1_1_1.configure(cursor="ibeam")

        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1_1 = ttk.Labelframe(self.TNotebook1_t1)
        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1_1.place(relx=0.72, rely=0.37
                , relheight=0.2, relwidth=0.25)
        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1_1.configure(text='''Credit''')
        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1_1.configure(width=150)
        self.TLabelframe1_1_1_1_1_1_1_1_1_1_1_1.configure(takefocus="0")

        self.TEntry1_1_1_1_1_1_1_1_1_1_1_1 = ttk.Entry(self.TLabelframe1_1_1_1_1_1_1_1_1_1_1_1)
        self.TEntry1_1_1_1_1_1_1_1_1_1_1_1.place(relx=0.07, rely=0.36
                , relheight=0.38, relwidth=0.84, y=-12, h=12)
        self.TEntry1_1_1_1_1_1_1_1_1_1_1_1.configure(takefocus="")
        self.TEntry1_1_1_1_1_1_1_1_1_1_1_1.configure(cursor="ibeam")

        self.TButton1_1 = ttk.Button(self.TNotebook1_t1)
        self.TButton1_1.place(relx=0.4, rely=0.67, height=25, width=96)
        self.TButton1_1.configure(takefocus="")
        self.TButton1_1.configure(text='''Ecrire''')






if __name__ == '__main__':
    vp_start_gui()



